#!/usr/bin/env bash

set -euo pipefail

source "$(dirname "$0")/common.sh"

require_base_env

WORKER_URL="$(worker_url)"
IMAGE="$(api_image)"
echo "Building API image: $IMAGE"
build_and_push_image "$ROOT_DIR/backend/Dockerfile.api" "$IMAGE"

ALLOW_FLAG="--no-allow-unauthenticated"
if [[ "${API_ALLOW_UNAUTHENTICATED}" == "true" ]]; then
  ALLOW_FLAG="--allow-unauthenticated"
fi

echo "Deploying API..."
gcloud run deploy "$API_SERVICE_NAME" \
  --project "$PROJECT_ID" \
  --region "$REGION" \
  --platform managed \
  --service-account "$RUNTIME_SERVICE_ACCOUNT_EMAIL" \
  $ALLOW_FLAG \
  --image "$IMAGE" \
  --set-env-vars \
ENVIRONMENT="$ENVIRONMENT",\
LOG_LEVEL="$LOG_LEVEL",\
GCP_PROJECT_ID="$PROJECT_ID",\
GCP_REGION="$REGION",\
FIRESTORE_DATABASE="$FIRESTORE_DATABASE",\
FIRESTORE_COLLECTION="$FIRESTORE_COLLECTION",\
JOB_REPOSITORY_MODE=firestore,\
JOB_QUEUE_MODE=cloud_tasks,\
CLOUD_TASKS_QUEUE_ID="$CLOUD_TASKS_QUEUE_ID",\
CLOUD_TASKS_SERVICE_ACCOUNT_EMAIL="$CLOUD_TASKS_SERVICE_ACCOUNT_EMAIL",\
WORKER_BASE_URL="$WORKER_URL",\
WORKER_AUDIENCE="$WORKER_URL",\
WORKER_AUTH_TOKEN="$WORKER_AUTH_TOKEN",\
MOCK_MODE="$MOCK_MODE",\
DOWNLOAD_TIMEOUT_SECONDS="$DOWNLOAD_TIMEOUT_SECONDS",\
MAX_DOCUMENT_SIZE_BYTES="$MAX_DOCUMENT_SIZE_BYTES",\
GEMINI_LOCATION="$GEMINI_LOCATION",\
GEMINI_MODEL_SIMPLE="$GEMINI_MODEL_SIMPLE",\
GEMINI_MODEL_COMPLEX="$GEMINI_MODEL_COMPLEX",\
MAX_EXTRACTION_CONCURRENCY="$MAX_EXTRACTION_CONCURRENCY",\
ENABLE_LLM_CROSS_VALIDATION="$ENABLE_LLM_CROSS_VALIDATION",\
ENABLE_LLM_LEGAL_ASSESSMENT="$ENABLE_LLM_LEGAL_ASSESSMENT"

echo "API URL: $(api_url)"
